
export const SAVE_FLIGHT_DONE = 'SAVE_FLIGHT_DONE';
export const SAVE_FLIGHT = 'SAVE_FLIGHT';
export const GET_FLIGHT_DONE = 'GET_FLIGHT_DONE';
export const GET_FLIGHT = 'GET_FLIGHT';

export const RECEIVE_FLIGHTS = 'RECEIVE_FLIGHTS';
export const GET_ALL_FLIGHTS = 'GET_ALL_FLIGHTS';
